# Site
repository: krzwiatrzyk/resume2
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Krzysztof Wiatrzyk
title: DevOps Engineer
email: krzwiatrzyk@protonmail.com
# email_title: Email (Email title override)
phone: 731704717
# phone_title: Phone (Phone title override)
website: krzwiatrzyk.pl
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: jekyllrb
github_username:  krzwiatrzyk
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: krzwiatrzyk
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: "G-QYRPCRSETX"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I love to automate stuff. That's why DevOps role and principles are great for me. 
  However, I believe in importance of programming skills and regardless of my role I like to write code and extend my skills. 
  One day I hope to be professional trainer in areas of Cloud and DevOps.

  My most anticipated areas of interests are:
    - Kubernetes
    - Homelab

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Blog
        # link: krzwiatrzyk.pl
        # link_text: Link Text
        additional_links:
          - title:  Site
            icon: fab fa-browser
            url: krzwiatrzyk.pl
        quote: >
          Personal blog with weekly technology reading and watching list.
        description: | 
          I have created this blog for three reasons:
            1. Writing articles
            2. Grouping videos, projects and articles from other poeple
            3. Managing application by myself
          
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Samsung Electronics
        sub_title: DevOps Engineer 
        caption: February 2020 - January 2021
        link: https://www.samsung.com
        quote: >
          Telecomunications.
        description: | 
          As a DevOps engineer my task was to improve upstream version of Kubernetes in the field of resource management (CPU, Memory, NUMA nodes). 
          It required writing new features in Golang programming language and also inclined range of other tasks such as: complex code reviews, code version control (rebases, merges, cherry-picks, etc.), working with Kubernetes community, writing unit and e2e tests, preparing test machines (tweaking Linux for Kubernetes, installing Kubernetes from scratch), researching new fields of improvement.

          **Technologies involved:** _Git, Golang, Kubernetes, Operator SDK, Linux, Docker, Github_
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Institution name
        sub_title: Qualifications (eg. BA Performing Arts)
        caption: Date Range (eg. 2016 - 2019)
        quote: >
          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Description of qualification
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
